[[mgr.prepend_keymap]]
on = "e"
run = "shell --block -- unar %h"
desc = "Extract archive with unar"

[[mgr.prepend_keymap]]
on = "T"
run = 'shell -- ~/Programme/Typora-linux-x64/Typora "$@" &'
desc = "Open in Typora"

[[mgr.prepend_keymap]]
on = "I"
run = 'shell -- gthumb "$@" &'
desc = "Open in gThumb"

[[mgr.prepend_keymap]]
on = "M"
run = 'shell --block -- mpv --no-video --term-osd-bar "$@"'
desc = "Play audio with mpv"

[[mgr.prepend_keymap]]
on = "B"
run = 'shell -- xdg-open "$@" &'
desc = "Open in browser (xdg-open)"
